### ISSUE TITLE
Issue with absolute path

### ISSUE THREAD

**Issue by IKVillanes** [davibernardos/ProfMapp#1]
Hi,
I'm having this issue. I think it is because there is a absolute path in Redator.java file **"/home/bernardo/Repositorio/..."**

```
RingsExtended
jun 04, 2018 4:08:00 PM br.com.processador.Redator escrita
SEVERE: null
java.io.FileNotFoundException: /home/bernardo/Repositorio/RingsExtended_log.txt (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at java.io.FileWriter.<init>(FileWriter.java:63)
	at br.com.processador.Redator.escrita(Redator.java:22)
	at br.com.processador.Principal.main(Principal.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
```

**Comment by davibernardos** [comment]
We fixed the code please try again.

**Tool execution**
- Download file profmapp.jar from the /Tool folder.
- Execute the following command: java -jar profmapp.jar
- Inform the path for the projects' source codes.

**Comment by IKVillanes** [comment]
Dear Davi,
The tool still does not work, it does not show any error and it does not show any action either. Here the results:

```
$ java -jar profmapp.jar 
Informe o diretório em que se encontra a amostra (Ex.: /home/bernardo/Repositorio/): 
/home/user/android-repository
1. Pedometer-master
Pedometer-master
2. accordion-master
accordion-master
3. DivideAndConquer
DivideAndConquer
4. 2048-android-master
2048-android-master
```
Thanks.

**Comment by davibernardos** [comment]
The result is stored in file (csv and txt).
It is saved in the same folder where the repository is.

However, there are new updates in the code.

**Repeat step:**
- Download file profmapp.jar from the /Tool folder.

**Comment by IKVillanes** [comment]
Hi,
Now with the new jar it's working, only one observation, with some apps the challenges report is empty.
Thanks!
